name: Java CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Confirm Setup
        run: echo "Java environment is ready!"

  verify:
    needs: setup  # This job runs AFTER setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Repository Contents
        run: ls -R && echo "Verification complete!"

      - name: Placeholder Test
        run: echo "No Java files found. This is a placeholder test for lab3-Hiba."
